@echo off
echo Starting Potato Disease Detection Backend...
cd backend
echo Activating conda environment from S:\mldeeplearningai...
call S:\mldeeplearningai\Scripts\activate.bat
echo Installing/updating dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
python main.py
pause
